# application.yaml equivalent of application.properties
spring:
  application:
    name: Pece Agencia v2 API
  boot.admin.client:
    url: http://localhost:8181
  datasource:
    url: jdbc:mysql://localhost:3306/agencia?createDatabaseIfNotExist=true
    username: root
    password: secret
    hikari:
      auto-commit: false
      transaction-isolation: TRANSACTION_READ_COMMITTED
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        type:
          format_sql: true
        highlight_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  data:
    jpa:
      repositories:
        enabled: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  security.oauth2.resourceserver.jwt:
    jwk-set-uri: ${keycloak.base-url}/realms/${keycloak.realm}/protocol/openid-connect/certs
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE
stripe:
  api-key: sk_test_12345
  base-url: http://localhost:12111
plataforma:
  hotel:
    regular:
      url: http://localhost:18080
    ng:
      url: http://localhost:18080
  empresa-aerea:
    url: http://localhost:18080
  locadora-veiculos:
    url: http://localhost:18080

management:
  endpoints:
    web:
      exposure:
        include: "*"

keycloak:
  realm: pece

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    urls:
      - name: v1
        url: /swagger/v1.yaml